---
name: auction
home: https://github.com/guilherme-roveri-movile/auction
sources:
- https://github.com/guilherme-roveri-movile/auction
version: @git.commit@
description: Sample Kotlin + Spring
maintainers:
- name: Guilherme Roveri
  email: gbroveri@gmail.com