---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auction
    commit: @git.commit@
  name: auction-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: auction